version: '3'
services:
  app:
    build: .
    image: hokm:latest
    environment:
      - HTTPS_PROXY=${HTTPS_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '6379:6379'