version: '3'
services:
  app:
    build: .
    image: hokm:latest
    environment:
      - HTTPS_PROXY=${HTTPS_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
    depends_on:
      - redis
    networks:
      - hokm-net
    ports:
      - '${SERVER_PORT}:9090'
      
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - hokm-net

networks:
  hokm-net:
    driver: bridge
